name: tests

on: [push]

jobs:
  no_ext_tests:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: true
      matrix:
        php: ['7.4','8.1','8.2','8.3']
        phpunit: ['8.5','10.5','10.5','10.5']
      max-parallel: 1
  
    steps:
      - name: Checkout codes
        uses: "actions/checkout@v2"

      - name: Composer
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          configuration: tests/phpunit.xml
          version: ${{ matrix.phpunit }}
          php_version: ${{ matrix.php }}
          php_extensions: gd
        env:
          TRAVIS_PHP_VERSION: true
